name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: gccemacs-darwin
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A emacsGccDarwin
    - run: echo OK
